baseURL = "https://cypherduckcom.github.io/"
languageCode = "en-us"
title = "Cypherduck"
theme = "hugo-dusk"
canonifyURLs = true

# Enable syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  description = "Cypherduck"
  # Social links (optional)
  # email = "your-email@example.com"
  # Color scheme options: auto, light, dark
  colorScheme = "auto"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

